import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { app, db } from '../firebase'
import {
  Container,
  Typography
} from '@mui/material';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    // checking if the browser has acess token
    let token = sessionStorage.getItem('Token');

    if(!token) {
      router.push('/login');
    }
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Spending Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Typography>Home</Typography>
      </Container>
      
    </div>
  )
}
